# docker-compose.test.yml

version: '3.7'

services:
  items:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/usr/src/avikus_backend
    ports:
      - 80:80
    depends_on:
      - test_db
    environment:
      - TEST_ENV=true  # 여기에서 TEST_ENV를 설정합니다.

  test_db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=test_username
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_items
    expose: 
      - 5432